language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

matrix:
    allow_failures:
        -   php: nightly

cache:
    directories:
        - vendor

sudo: false

install:
    - if [[ "${TRAVIS_PHP_VERSION}" == "nightly" ]]; then composer install --ignore-platform-reqs; fi
    - if [[ "${TRAVIS_PHP_VERSION}" != "nightly" ]]; then composer install; fi

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
